### ISSUE TITLE
Chat Flow

### ISSUE THREAD

**Issue by cmastral** [cmastral/sprint1#1]
How the chat will flow. Every possible conversation based on the options that the chatbot gives.
Greeting, Buy/Sell Options, Result text,Wrong input

**Comment by georgepatrik** [comment]
![54401904_428094197963084_7077916751584821248_n.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c7d1e626dcafe00131e265a/125516c66e82c728ace21e0d46bdc0ce73d3daf9dbd6eb11fc0da9c0781f702a7f57f37324bab478e815225059584bad44505b4cfef88b2faed96262964e4baf8e370a27822f1bbebdd118ea06b229d84786e3ef8d19c0ea3522e4da88476c4d17049bbd0c6bf4c6169112a309f34747a51b3c62e373347f4e9317752b6b6721b9b1.jpg)

**Comment by georgepatrik** [comment]
We should reconsider the "No" on SELL FLOW. It  might be better to use "Yes or Immediate entry". What do you think?
